import type { Category, Product, Review, Coupon, Banner } from './types';
import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const categories: Category[] = [
  { id: '1', name: 'Electronics', slug: 'electronics', image: findImage('category-electronics') },
  { id: '2', name: 'Fashion', slug: 'fashion', image: findImage('category-fashion') },
  { id: '3', name: 'Home & Kitchen', slug: 'home', image: findImage('category-home') },
  { id: '4', name: 'Beauty', slug: 'beauty', image: findImage('category-beauty') },
  { id: '5', name: 'Sports', slug: 'sports', image: findImage('category-sports') },
  { id: '6', name: 'Books', slug: 'books', image: findImage('category-books') },
  { id: '7', name: 'Grocery', slug: 'grocery', image: findImage('category-grocery') },
];

export const products: Product[] = [
  // Electronics
  {
    id: '1',
    name: 'QuantumBook Pro',
    description: 'The future of computing is here. With a blazing fast quantum processor and a stunning 4K display, the QuantumBook Pro is the ultimate laptop for professionals.',
    images: [findImage('product-1-a'), findImage('product-1-b'), 'https://picsum.photos/seed/p1c/600/600', 'https://picsum.photos/seed/p1d/600/600'],
    price: 1999,
    mrp: 2499,
    category: 'electronics',
    brand: 'Quantum',
    rating: 4.8,
    reviewsCount: 120,
    inStock: true,
    attributes: { 'RAM': '16GB', 'Storage': '1TB SSD' },
    tags: ['laptop', 'pro', '4k']
  },
  {
    id: '2',
    name: 'StellarPhone 12',
    description: 'Capture the universe with the StellarPhone 12. Its advanced camera system and long-lasting battery make it the perfect companion for your adventures.',
    images: [findImage('product-2-a'), 'https://picsum.photos/seed/p2b/600/600'],
    price: 799,
    mrp: 999,
    category: 'electronics',
    brand: 'Stellar',
    rating: 4.5,
    reviewsCount: 250,
    inStock: true,
    attributes: { 'Color': 'Cosmic Blue', 'Storage': '256GB' },
    tags: ['smartphone', 'camera']
  },
  {
    id: '11',
    name: 'EchoBuds Pro',
    description: 'Immersive sound, active noise cancellation, and seamless integration with your smart devices.',
    images: ['https://picsum.photos/seed/p11a/600/600', 'https://picsum.photos/seed/p11b/600/600'],
    price: 129.99,
    mrp: 159.99,
    category: 'electronics',
    brand: 'Stellar',
    rating: 4.6,
    reviewsCount: 340,
    inStock: true,
    attributes: { 'Color': 'White', 'Connectivity': 'Bluetooth 5.2' },
    tags: ['earbuds', 'audio', 'anc']
  },
  {
    id: '12',
    name: 'GamerX-Pro Keyboard',
    description: 'Mechanical gaming keyboard with customizable RGB lighting and programmable macro keys.',
    images: ['https://picsum.photos/seed/p12a/600/600'],
    price: 89.99,
    mrp: 119.99,
    category: 'electronics',
    brand: 'Quantum',
    rating: 4.9,
    reviewsCount: 95,
    inStock: false,
    attributes: { 'Switch Type': 'Blue Mechanical', 'Layout': 'Full-size' },
    tags: ['keyboard', 'gaming', 'rgb']
  },
  {
    id: '20',
    name: 'Smart Watch 5',
    description: 'Stay connected and track your fitness goals with the new Smart Watch 5.',
    images: ['https://picsum.photos/seed/p20a/600/600'],
    price: 249.99,
    mrp: 299.99,
    category: 'electronics',
    brand: 'Stellar',
    rating: 4.3,
    reviewsCount: 180,
    inStock: true,
    attributes: { 'Color': 'Space Gray', 'Band': 'Silicone' },
    tags: ['smartwatch', 'fitness', 'wearable']
  },
  {
    id: '21',
    name: '4K Ultra HD Monitor',
    description: 'A 27-inch 4K UHD monitor with stunning color accuracy and clarity. Perfect for creative professionals.',
    images: ['https://picsum.photos/seed/p21a/600/600', 'https://picsum.photos/seed/p21b/600/600'],
    price: 499.99,
    mrp: 649.99,
    category: 'electronics',
    brand: 'Quantum',
    rating: 4.7,
    reviewsCount: 150,
    inStock: true,
    attributes: { 'Size': '27-inch', 'Resolution': '3840x2160' },
    tags: ['monitor', '4k', 'display']
  },
  {
    id: '22',
    name: 'Nebula Streaming Stick',
    description: 'Stream your favorite movies and shows in 4K HDR. Easy setup and a simple remote.',
    images: ['https://picsum.photos/seed/p22a/600/600'],
    price: 49.99,
    mrp: 59.99,
    category: 'electronics',
    brand: 'Stellar',
    rating: 4.6,
    reviewsCount: 850,
    inStock: true,
    attributes: { 'Resolution': '4K HDR', 'Platform': 'Android TV' },
    tags: ['streaming', 'media', 'tv']
  },

  // Fashion
  {
    id: '3',
    name: 'Urban Explorer Jacket',
    description: 'A stylish and functional jacket for the modern urbanite. Waterproof, windproof, and breathable.',
    images: [findImage('product-3-a'), 'https://picsum.photos/seed/p3b/600/600'],
    price: 120,
    mrp: 180,
    category: 'fashion',
    brand: 'UrbanFlex',
    rating: 4.7,
    reviewsCount: 88,
    inStock: true,
    attributes: { 'Color': 'Midnight Black', 'Size': 'L' },
    tags: ['jacket', 'outerwear', 'men']
  },
  {
    id: '4',
    name: 'Classic Denim Jeans',
    description: 'Timeless style meets modern comfort. Made with premium stretch denim for the perfect fit.',
    images: [findImage('product-4-a')],
    price: 60,
    mrp: 85,
    category: 'fashion',
    brand: 'DenimCo',
    rating: 4.6,
    reviewsCount: 310,
    inStock: true,
    attributes: { 'Color': 'Indigo Wash', 'Size': '32/32' },
    tags: ['jeans', 'denim', 'unisex']
  },
  {
    id: '13',
    name: 'Flowy Summer Dress',
    description: 'Light and airy, this floral print dress is perfect for warm weather and sunny days.',
    images: ['https://picsum.photos/seed/p13a/600/600'],
    price: 75,
    mrp: 100,
    category: 'fashion',
    brand: 'UrbanFlex',
    rating: 4.4,
    reviewsCount: 125,
    inStock: true,
    attributes: { 'Color': 'Floral', 'Size': 'M' },
    tags: ['dress', 'women', 'summer']
  },
  {
    id: '14',
    name: 'LeatherCraft Loafers',
    description: 'Hand-stitched genuine leather loafers that blend classic style with all-day comfort.',
    images: ['https://picsum.photos/seed/p14a/600/600'],
    price: 150,
    mrp: 220,
    category: 'fashion',
    brand: 'DenimCo',
    rating: 4.8,
    reviewsCount: 65,
    inStock: true,
    attributes: { 'Color': 'Brown', 'Size': '10' },
    tags: ['shoes', 'leather', 'formal']
  },
  {
    id: '23',
    name: 'Silk Blend Scarf',
    description: 'An elegant silk blend scarf with a vibrant abstract print. Adds a touch of class to any outfit.',
    images: ['https://picsum.photos/seed/p23a/600/600'],
    price: 45,
    mrp: 65,
    category: 'fashion',
    brand: 'UrbanFlex',
    rating: 4.9,
    reviewsCount: 72,
    inStock: true,
    attributes: { 'Material': 'Silk Blend', 'Pattern': 'Abstract' },
    tags: ['scarf', 'accessory', 'women']
  },
  {
    id: '24',
    name: 'Performance Polo Shirt',
    description: 'Moisture-wicking and breathable polo shirt, perfect for the golf course or a casual day out.',
    images: ['https://picsum.photos/seed/p24a/600/600'],
    price: 55,
    mrp: 70,
    category: 'fashion',
    brand: 'DenimCo',
    rating: 4.7,
    reviewsCount: 130,
    inStock: true,
    attributes: { 'Color': 'Navy Blue', 'Size': 'M' },
    tags: ['polo', 'shirt', 'men']
  },

  // Home & Kitchen
  {
    id: '5',
    name: 'Velvet Cloud Sofa',
    description: 'Sink into the luxurious comfort of the Velvet Cloud Sofa. Perfect for movie nights and lazy Sundays.',
    images: [findImage('product-5-a'), 'https://picsum.photos/seed/p5b/600/600'],
    price: 899,
    mrp: 1200,
    category: 'home',
    brand: 'ComfyHome',
    rating: 4.9,
    reviewsCount: 45,
    inStock: true,
    attributes: { 'Color': 'Forest Green', 'Material': 'Velvet' },
    tags: ['sofa', 'furniture', 'living room']
  },
  {
    id: '6',
    name: 'SmartBrew Coffee Maker',
    description: 'Brew the perfect cup of coffee from your phone. The SmartBrew connects to WiFi for ultimate convenience.',
    images: [findImage('product-6-a')],
    price: 150,
    mrp: 200,
    category: 'home',
    brand: 'KitchenWiz',
    rating: 4.7,
    reviewsCount: 150,
    inStock: false,
    attributes: { 'Capacity': '12-cup', 'Color': 'Stainless Steel' },
    tags: ['coffee', 'kitchen', 'smart home']
  },
  {
    id: '15',
    name: 'Aero-Dyne Air Purifier',
    description: 'Breathe cleaner air with the Aero-Dyne Air Purifier, featuring a HEPA filter that captures 99.97% of airborne particles.',
    images: ['https://picsum.photos/seed/p15a/600/600'],
    price: 199.99,
    mrp: 249.99,
    category: 'home',
    brand: 'KitchenWiz',
    rating: 4.8,
    reviewsCount: 180,
    inStock: true,
    attributes: { 'Coverage': '350 sq ft', 'Color': 'White' },
    tags: ['air purifier', 'health', 'home appliance']
  },
  {
    id: '25',
    name: 'RoboVac S1',
    description: 'An intelligent robot vacuum that cleans your floors so you don\'t have to. Controllable via app.',
    images: ['https://picsum.photos/seed/p25a/600/600'],
    price: 299,
    mrp: 450,
    category: 'home',
    brand: 'ComfyHome',
    rating: 4.6,
    reviewsCount: 220,
    inStock: true,
    attributes: { 'Suction Power': '2000Pa', 'Runtime': '100 mins' },
    tags: ['vacuum', 'robot', 'smart home']
  },
  {
    id: '26',
    name: 'Pro-Chef Knife Set',
    description: 'A 15-piece high-carbon stainless steel knife set with a wooden block. Sharp, durable, and rust-resistant.',
    images: ['https://picsum.photos/seed/p26a/600/600'],
    price: 125,
    mrp: 180,
    category: 'home',
    brand: 'KitchenWiz',
    rating: 4.9,
    reviewsCount: 310,
    inStock: true,
    attributes: { 'Pieces': '15', 'Material': 'Stainless Steel' },
    tags: ['kitchen', 'knives', 'cooking']
  },

  // Beauty
  {
    id: '7',
    name: 'RadiantGlow Serum',
    description: 'Unlock your skin\'s natural radiance. This Vitamin C serum brightens and evens skin tone.',
    images: [findImage('product-7-a')],
    price: 45,
    mrp: 60,
    category: 'beauty',
    brand: 'Ethereal',
    rating: 4.8,
    reviewsCount: 500,
    inStock: true,
    attributes: { 'Volume': '30ml', 'Skin Type': 'All' },
    tags: ['skincare', 'serum', 'vitamin c']
  },
  {
    id: '16',
    name: 'MatteFinish Lipstick Set',
    description: 'A set of 5 long-lasting, smudge-proof matte lipsticks in a range of vibrant shades.',
    images: ['https://picsum.photos/seed/p16a/600/600'],
    price: 35,
    mrp: 50,
    category: 'beauty',
    brand: 'Ethereal',
    rating: 4.5,
    reviewsCount: 210,
    inStock: true,
    attributes: { 'Count': '5 pieces', 'Finish': 'Matte' },
    tags: ['makeup', 'lipstick', 'cosmetics']
  },
  {
    id: '27',
    name: 'HydraBoost Moisturizer',
    description: 'A lightweight, oil-free moisturizer that provides 24-hour hydration for soft, supple skin.',
    images: ['https://picsum.photos/seed/p27a/600/600'],
    price: 38,
    mrp: 52,
    category: 'beauty',
    brand: 'Ethereal',
    rating: 4.7,
    reviewsCount: 680,
    inStock: true,
    attributes: { 'Volume': '50ml', 'Skin Type': 'Normal to Dry' },
    tags: ['skincare', 'moisturizer', 'face']
  },
  {
    id: '28',
    name: 'LushLash Mascara',
    description: 'Volumizing and lengthening mascara for dramatic, eye-opening lashes without clumping.',
    images: ['https://picsum.photos/seed/p28a/600/600'],
    price: 24,
    mrp: 30,
    category: 'beauty',
    brand: 'Ethereal',
    rating: 4.6,
    reviewsCount: 450,
    inStock: false,
    attributes: { 'Color': 'Black', 'Effect': 'Volumizing' },
    tags: ['makeup', 'mascara', 'eyes']
  },

  // Sports
  {
    id: '8',
    name: 'Aero-Stride Running Shoes',
    description: 'Feel like you\'re running on air. Lightweight, responsive, and designed for maximum performance.',
    images: [findImage('product-8-a')],
    price: 130,
    mrp: 160,
    category: 'sports',
    brand: 'FitRun',
    rating: 4.7,
    reviewsCount: 220,
    inStock: true,
    attributes: { 'Color': 'Electric Blue', 'Size': '10' },
    tags: ['running', 'shoes', 'sports']
  },
  {
    id: '17',
    name: 'Pro-Grip Yoga Mat',
    description: 'Eco-friendly and non-slip yoga mat for a stable and comfortable practice.',
    images: ['https://picsum.photos/seed/p17a/600/600'],
    price: 40,
    mrp: 55,
    category: 'sports',
    brand: 'FitRun',
    rating: 4.9,
    reviewsCount: 400,
    inStock: true,
    attributes: { 'Material': 'TPE', 'Thickness': '6mm' },
    tags: ['yoga', 'fitness', 'exercise']
  },
  {
    id: '29',
    name: 'Adjustable Dumbbell Set',
    description: 'A versatile dumbbell set that adjusts from 5 to 52.5 lbs, saving space in your home gym.',
    images: ['https://picsum.photos/seed/p29a/600/600'],
    price: 399,
    mrp: 549,
    category: 'sports',
    brand: 'FitRun',
    rating: 4.8,
    reviewsCount: 190,
    inStock: true,
    attributes: { 'Weight Range': '5-52.5 lbs', 'Material': 'Steel' },
    tags: ['fitness', 'gym', 'weights']
  },
  {
    id: '30',
    name: 'HydraFlow Water Bottle',
    description: 'A 32oz insulated stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12.',
    images: ['https://picsum.photos/seed/p30a/600/600'],
    price: 25,
    mrp: 35,
    category: 'sports',
    brand: 'FitRun',
    rating: 4.9,
    reviewsCount: 1100,
    inStock: true,
    attributes: { 'Capacity': '32oz', 'Color': 'Matte Black' },
    tags: ['hydration', 'bottle', 'accessory']
  },

  // Books
  {
    id: '9',
    name: 'The Last Horizon',
    description: 'A thrilling sci-fi epic about humanity\'s last-ditch effort to find a new home among the stars.',
    images: [findImage('product-9-a')],
    price: 15.99,
    mrp: 25.99,
    category: 'books',
    brand: 'Jane Doe', // Author as brand
    rating: 4.9,
    reviewsCount: 1250,
    inStock: true,
    attributes: { 'Format': 'Paperback', 'Author': 'Jane Doe' },
    tags: ['sci-fi', 'fiction', 'bestseller']
  },
  {
    id: '18',
    name: 'The Art of Mindful Cooking',
    description: 'A cookbook that combines delicious recipes with the practice of mindfulness in the kitchen.',
    images: ['https://picsum.photos/seed/p18a/600/600'],
    price: 22.50,
    mrp: 30,
    category: 'books',
    brand: 'John Smith',
    rating: 4.7,
    reviewsCount: 98,
    inStock: true,
    attributes: { 'Format': 'Hardcover', 'Author': 'John Smith' },
    tags: ['cookbook', 'mindfulness', 'non-fiction']
  },
  {
    id: '31',
    name: 'Echoes of a Forgotten City',
    description: 'A gripping historical fiction novel set in ancient Rome, following the life of a gladiator.',
    images: ['https://picsum.photos/seed/p31a/600/600'],
    price: 14.99,
    mrp: 22.99,
    category: 'books',
    brand: 'Markus Aurelius',
    rating: 4.8,
    reviewsCount: 880,
    inStock: true,
    attributes: { 'Format': 'Paperback', 'Author': 'Markus Aurelius' },
    tags: ['historical', 'fiction', 'rome']
  },
  {
    id: '32',
    name: 'Atomic Habits',
    description: 'An easy & proven way to build good habits & break bad ones. By James Clear.',
    images: ['https://picsum.photos/seed/p32a/600/600'],
    price: 18.00,
    mrp: 27.00,
    category: 'books',
    brand: 'James Clear',
    rating: 4.9,
    reviewsCount: 15000,
    inStock: true,
    attributes: { 'Format': 'Hardcover', 'Author': 'James Clear' },
    tags: ['self-help', 'productivity', 'non-fiction']
  },

  // Grocery
  {
    id: '10',
    name: 'Organic Honeycrisp Apples',
    description: 'Crisp, juicy, and sweet. These organic Honeycrisp apples are a healthy and delicious snack.',
    images: [findImage('product-10-a')],
    price: 5.99,
    mrp: 7.99,
    category: 'grocery',
    brand: 'FreshFarms',
    rating: 4.9,
    reviewsCount: 300,
    inStock: true,
    attributes: { 'Weight': '2 lbs' },
    tags: ['fruit', 'organic', 'fresh']
  },
  {
    id: '19',
    name: 'Artisanal Sourdough Bread',
    description: 'Freshly baked sourdough loaf with a crispy crust and a soft, chewy interior.',
    images: ['https://picsum.photos/seed/p19a/600/600'],
    price: 8.50,
    mrp: 10,
    category: 'grocery',
    brand: 'FreshFarms',
    rating: 4.9,
    reviewsCount: 150,
    inStock: true,
    attributes: { 'Type': 'Sourdough' },
    tags: ['bakery', 'bread', 'fresh']
  },
  {
    id: '33',
    name: 'Cage-Free Brown Eggs',
    description: 'One dozen large brown cage-free eggs. Sourced from pasture-raised hens.',
    images: ['https://picsum.photos/seed/p33a/600/600'],
    price: 4.99,
    mrp: 5.99,
    category: 'grocery',
    brand: 'FreshFarms',
    rating: 4.8,
    reviewsCount: 250,
    inStock: true,
    attributes: { 'Quantity': '12 count' },
    tags: ['dairy', 'eggs', 'organic']
  },
  {
    id: '34',
    name: 'Gourmet Dark Chocolate Bar',
    description: 'A rich and intense 72% cacao dark chocolate bar with notes of cherry and coffee.',
    images: ['https://picsum.photos/seed/p34a/600/600'],
    price: 3.99,
    mrp: 4.99,
    category: 'grocery',
    brand: 'ChocoLux',
    rating: 4.9,
    reviewsCount: 400,
    inStock: true,
    attributes: { 'Cacao': '72%', 'Weight': '100g' },
    tags: ['chocolate', 'snack', 'gourmet']
  }
];

export const reviews: Review[] = [
  { id: '1', productId: '1', author: 'Alex R.', rating: 5, title: 'Incredible Machine!', comment: 'This laptop is faster than anything I\'ve ever used. The display is gorgeous. Worth every penny.', date: '2023-10-15' },
  { id: '2', productId: '1', author: 'Sam K.', rating: 4, title: 'Great, but expensive', comment: 'It\'s a fantastic laptop, but the price is steep. You get what you pay for though.', date: '2023-10-12' },
  { id: '3', productId: '1', author: 'Casey B.', rating: 5, title: 'Flawless performance', comment: 'I use this for video editing and it handles everything I throw at it with ease. The keyboard is also a joy to type on.', date: '2023-10-11' },
  { id: '4', productId: '2', author: 'Maria G.', rating: 5, title: 'Best phone camera', comment: 'I bought this for the camera and it did not disappoint. The photos are stunning!', date: '2023-09-20' },
  { id: '5', productId: '2', author: 'David L.', rating: 4, title: 'Solid phone, great display', comment: 'The screen is bright and responsive. Battery life gets me through the day easily. A great upgrade.', date: '2023-09-18' },
  { id: '6', productId: '4', author: 'John D.', rating: 5, title: 'Perfect fit and feel', comment: 'These are the most comfortable jeans I\'ve ever owned. Great quality.', date: '2023-11-01' },
  { id: '7', productId: '5', author: 'Emily W.', rating: 5, title: 'Absolutely in love!', comment: 'This sofa is the centerpiece of my living room. It\'s so comfortable and the color is even more beautiful in person.', date: '2023-10-25' },
  { id: '8', productId: '7', author: 'Sophia T.', rating: 5, title: 'Visible difference', comment: 'My skin looks so much brighter after just a few weeks of using this serum. It\'s now a staple in my routine.', date: '2023-11-02' },
  { id: '9', productId: '9', author: 'Bookworm22', rating: 5, title: 'Couldn\'t put it down!', comment: 'An absolute masterpiece of science fiction. The world-building is incredible and the characters are so compelling.', date: '2023-08-05' },
];

export const coupons: Coupon[] = [
    { code: 'SAVE10', type: 'percentage', value: 10, description: 'Get 10% off your entire order.' },
    { code: 'FLAT50', type: 'flat', value: 50, description: 'Get a flat $50 discount on orders over $500.' },
    { code: 'FREESHIP', type: 'shipping', value: 0, description: 'Free shipping on your order.' },
];

export const banners: Banner[] = [
  { id: '1', title: 'Huge Electronics Sale', description: 'Up to 40% off on Laptops, Phones, and more!', imageUrl: findImage('banner-1'), link: '/category/electronics' },
  { id: '2', title: 'New Fashion Arrivals', description: 'Discover the latest trends for the new season.', imageUrl: findImage('banner-2'), link: '/category/fashion' },
  { id: '3', title: 'Cozy Up Your Home', description: 'Find the perfect decor to refresh your space.', imageUrl: findImage('banner-3'), link: '/category/home' },
];
